spring.application.name=spring-boot-web
# server.port=8081

spring.datasource.url=jdbc:mysql://ec2-13-209-76-42.ap-northeast-2.compute.amazonaws.com:3306/COSMAX
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.username=cosmax_dba
spring.datasource.password=1p2@3s4$5k6

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
# XSUAA 설정
sap.security.services.xsuaa.url=https://d4112408trial.authentication.ap21.hana.ondemand.com
sap.security.services.xsuaa.clientid=sb-na-5806ca69-a84a-4c2f-858d-17281181fb04!t56771
sap.security.services.xsuaa.clientsecret=38cd8bf6-e008-47c2-97a1-7befa4a6f020$U24b_bcZPt_QJ1PGEKXzYOaF8O0RBY3Sccd1rg_CNd0=
sap.security.services.xsuaa.xsappname=na-5806ca69-a84a-4c2f-858d-17281181fb04!t56771
sap.security.services.xsuaa.identityzone=d4112408trial
sap.security.services.xsuaa.identityzoneid=95050a00-024b-459d-a29a-2bb5a7e01096
sap.security.services.xsuaa.tenantid=95050a00-024b-459d-a29a-2bb5a7e01096
sap.security.services.xsuaa.uaadomain=authentication.ap21.hana.ondemand.com
sap.security.services.xsuaa.apiurl=https://api.authentication.ap21.hana.ondemand.com

# JWK set URI for JWT validation
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://d4112408trial.authentication.ap21.hana.ondemand.com/oauth/token_keys

# 기본 서버 포트 설정
server.port=8080


